In [1]:
import pandas as pd
import numpy as np


In [4]:
df = pd.read_csv('Recommend.csv')
df

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [5]:
from sklearn.model_selection import train_test_split
n_users = df.user_id.unique().shape[0]
n_movies = df.movie_id.unique().shape[0]

train_data, test_data = train_test_split(df,test_size=0.25)

In [6]:
train_data_matrix = np.zeros((n_users, n_movies))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

train_data_matrix

array([[5., 3., 4., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [7]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]
    
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
from sklearn.metrics import pairwise_distances
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
movie_similarity = pairwise_distances(train_data_matrix.T,metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]

ratings_diff = (train_data_matrix -mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(ratings_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T

user_pred

array([[ 1.58276456,  0.61228815,  0.49562619, ...,  0.32392222,
         0.32385   ,  0.32365111],
       [ 1.33189515,  0.30846575,  0.14541145, ..., -0.05553736,
        -0.05418423, -0.05410654],
       [ 1.32347978,  0.26629983,  0.111018  , ..., -0.09421555,
        -0.09253398, -0.09240034],
       ...,
       [ 1.17892089,  0.22047864,  0.06363621, ..., -0.13034111,
        -0.12925883, -0.12932332],
       [ 1.35917737,  0.33625597,  0.20349046, ...,  0.0060087 ,
         0.00694226,  0.00716718],
       [ 1.39888426,  0.40252666,  0.29132121, ...,  0.1171974 ,
         0.1170468 ,  0.11715811]])